apiVersion: v1
kind: Secret

metadata:
  name: enterprise-ai-etl-secret

type: Opaque

stringData:

  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"

  EMAIL_PASSWORD: "YOUR_GMAIL_APP_PASSWORD"

  JIRA_API_TOKEN: "YOUR_JIRA_API_TOKEN"

  SNOWFLAKE_PASSWORD: "YOUR_SNOWFLAKE_PASSWORD"