from .config import client

from .secrets import (
    JIRA_URL,
    JIRA_USERNAME,
    JIRA_API_TOKEN,

    SMTP_SERVER,
    SMTP_PORT,
    EMAIL_USER,
    EMAIL_PASSWORD,

    SNOWFLAKE_ACCOUNT,
    SNOWFLAKE_USER,
    SNOWFLAKE_PASSWORD,
    SNOWFLAKE_DATABASE,
    SNOWFLAKE_SCHEMA,
    SNOWFLAKE_WAREHOUSE,
    SNOWFLAKE_ROLE,
)

__all__ = [
    "client",

    "JIRA_URL",
    "JIRA_USERNAME",
    "JIRA_API_TOKEN",

    "SMTP_SERVER",
    "SMTP_PORT",
    "EMAIL_USER",
    "EMAIL_PASSWORD",

    "SNOWFLAKE_ACCOUNT",
    "SNOWFLAKE_USER",
    "SNOWFLAKE_PASSWORD",
    "SNOWFLAKE_DATABASE",
    "SNOWFLAKE_SCHEMA",
    "SNOWFLAKE_WAREHOUSE",
    "SNOWFLAKE_ROLE",
]