apiVersion: batch/v1
kind: Job

metadata:
  name: enterprise-ai-etl-framework

spec:
  backoffLimit: 0

  template:

    metadata:
      labels:
        app: enterprise-ai-etl-framework

    spec:

      restartPolicy: Never

      containers:

      - name: enterprise-ai-etl-framework

        image: saginalavenkat/enterprise-ai-etl-framework:1.0

        imagePullPolicy: Always

        envFrom:

        - secretRef:
            name: enterprise-ai-etl-secret

        - configMapRef:
            name: enterprise-ai-etl-config