"""
===============================================================================
File Name   : sql_agent.py
Project     : Enterprise AI ETL Framework
Purpose     : AI SQL Generation Agent
Author      : Venkata
===============================================================================
"""

from agents.base_agent import BaseAgent
from core.logger.logger import logger

from integrations.mcp.mcp_client import MCPClient
from integrations.mcp.tool_call import ToolCall
from knowledge.rag.rag_pipeline import RAGPipeline


class SQLAgent(BaseAgent):

    def __init__(self, rag_pipeline):

        super().__init__("SQL Agent", rag_pipeline)

        self.mcp_client = MCPClient()

        logger.info("SQL Agent Initialized.")

    def is_sql(self, text: str):

        sql_keywords = ["SELECT", "INSERT", "UPDATE", "DELETE", "MERGE", "WITH"]

        text = text.upper()

        return any(keyword in text for keyword in sql_keywords)

    def clean_sql(self, sql: str):

        """ Remove markdown and unnecessary text from GPT response. """

        sql = sql.replace("```sql", "")
        sql = sql.replace("```", "")
        sql = sql.strip()

        return sql

    def get_mock_response(self):

        return """ SELECT * FROM EMPLOYEE WHERE DEPARTMENT='IT' AND SALARY > 90000; """

    def execute(self, context):

        logger.info("SQL Agent Started.")

        prompt = f"""Requirement {context.requirement} Mapping {context.mapping} Test Cases {context.test_cases} Generate SQL Query only."""

        generated_sql = self.ask_llm(prompt)
        context.metrics.add_tokens(500)
        generated_sql = self.clean_sql(generated_sql)

        logger.info("Generated SQL:\n%s", generated_sql)

        if not self.is_sql(generated_sql):

            raise Exception("Invalid SQL generated by GPT.")

        tool_call = ToolCall(tool_name="database", arguments={"database": "snowflake", "query": generated_sql})

        response = self.mcp_client.execute(tool_call)

        context.generated_sql = generated_sql

        context.query_result = response

        logger.info("SQL Execution Completed.")

        return context

# ------------------------------------------------------------
# Testing
# ------------------------------------------------------------

if __name__ == "__main__":

    from core.workflows.workflow_context import WorkflowContext

    rag_pipeline = RAGPipeline()

    agent = SQLAgent(rag_pipeline)

    context = WorkflowContext("Employee Query")

    context.requirement = "Show IT Employees"

    context.mapping = "EMPLOYEE Mapping"

    context.test_cases = "Validate Salary"

    context = agent.execute(context)

    print(context.to_dict())