"""
===============================================================================
File Name   : sql_agent.py
Project     : Enterprise AI ETL Framework
Purpose     : AI SQL Generation Agent
Author      : Venkata
===============================================================================
"""

from agents.base_agent import BaseAgent
from core.logger.logger import logger

from integrations.mcp.mcp_client import MCPClient
from integrations.mcp.tool_call import ToolCall


class SQLAgent(BaseAgent):
    """
    AI Agent responsible for SQL Generation and Execution.
    """

    def __init__(
            self,
            rag_pipeline=None,
            client=None,
            mcp_client=None
    ):

        super().__init__(
            agent_name="SQL Agent",
            rag_pipeline=rag_pipeline,
            client=client
        )

        self.mcp_client = mcp_client or MCPClient()

    # ------------------------------------------------------------------
    # Validate SQL
    # ------------------------------------------------------------------

    def is_sql(self, text) -> bool:

        if not text:
            return False

        text = text.strip().upper()

        sql_keywords = (
            "SELECT",
            "INSERT",
            "UPDATE",
            "DELETE",
            "MERGE",
            "WITH"
        )

        return text.startswith(tuple(sql_keywords))

    # ------------------------------------------------------------------
    # Clean SQL
    # ------------------------------------------------------------------

    def clean_sql(self, sql: str) -> str:
        """
        Removes markdown formatting from GPT response.
        """

        sql = sql.replace("```sql", "")
        sql = sql.replace("```", "")

        return sql.strip()

    # ------------------------------------------------------------------
    # Mock Response
    # ------------------------------------------------------------------

    def get_mock_response(self):

        return (
            "SELECT * FROM EMPLOYEE "
            "WHERE DEPARTMENT='IT' "
            "AND SALARY > 90000;"
        )

    # ------------------------------------------------------------------
    # Execute
    # ------------------------------------------------------------------

    def execute(self, context):

        logger.info("=" * 80)
        logger.info("SQL Agent Started.")
        logger.info("=" * 80)

        prompt = f"""
        Requirement
        {context.requirement}

        Mapping
        {context.mapping}

        Test Cases
        {context.test_cases}

        Generate ONLY a valid Snowflake SQL query.

        Rules:
        1. Return SQL only.
        2. Do not explain.
        3. Do not use markdown.
        4. Do not wrap inside ```sql."""

        generated_sql = self.ask_llm(
            question=prompt,
            context=context
        )

        generated_sql = self.clean_sql(generated_sql)

        if not self.is_sql(generated_sql):

            logger.warning(
                "Invalid SQL generated by GPT. "
                "Using Mock SQL."
            )

            generated_sql = self.get_mock_response()

        generated_sql = self.clean_sql(generated_sql)

        logger.info("Generated SQL:\n%s", generated_sql)

        tool_call = ToolCall(
            tool_name="database",
            arguments={
                "database": "snowflake",
                "query": generated_sql, "monitor": context.monitor})

        logger.info("Executing SQL using MCP Database Tool...")

        try:

            response = self.mcp_client.execute(tool_call)

        except Exception:

            logger.exception("SQL Execution Failed.\nSQL:\n%s", generated_sql)

            response = []

        context.generated_sql = generated_sql
        context.query_result = response

        print(type(context.query_result))
        print(context.query_result)

        logger.info("SQL Execution Completed.")

        return context